### ISSUE TITLE
biom in R 3.3.2

### ISSUE THREAD

**Issue by jokelley** [joey711/biom#23]
Hello, I am trying to use biom in QIIME. and I am getting the following error when I run $biom on the command line:

**Comment by jokelley** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/biom", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'biom-format==2.1.5' distribution was not found and is required by the application

I tried also installing biom in R
Warning message:
package ‘biom’ is not available (for R version 3.3.2)

**Comment by jnpaulson** [comment]
Biom package is deprecated. Use biomformat available in bioconductorOn Feb 15, 2017 4:22 PM, Joanna Kelley <notifications@github.com> wrote:Traceback (most recent call last):
File "/usr/local/bin/biom", line 5, in 
from pkg_resources import load_entry_point
File "/usr/lib/python2.7/dist-packages/pkg_resources/init.py", line 2927, in 
@_call_aside
File "/usr/lib/python2.7/dist-packages/pkg_resources/init.py", line 2913, in _call_aside
f(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/pkg_resources/init.py", line 2940, in _initialize_master_working_set
working_set = WorkingSet._build_master()
File "/usr/lib/python2.7/dist-packages/pkg_resources/init.py", line 637, in _build_master
return cls._build_from_requirements(requires)
File "/usr/lib/python2.7/dist-packages/pkg_resources/init.py", line 650, in _build_from_requirements
dists = ws.resolve(reqs, Environment())
File "/usr/lib/python2.7/dist-packages/pkg_resources/init.py", line 829, in resolve
raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'biom-format==2.1.5' distribution was not found and is required by the application
I tried also installing biom in R
Warning message:
package ‘biom’ is not available (for R version 3.3.2)

**Comment by jokelley** [comment]
That's not working either: 

> biocLite("biomformat")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.2 (BiocInstaller 1.20.3), R 3.3.2 (2016-10-31).
Installing package(s) ‘biomformat’
Warning message:
package ‘biomformat’ is not available (for R version 3.3.2)

**Comment by jnpaulson** [comment]
You're using an old version of bioconductor you need to upgrade using biocUpgrade()On Feb 15, 2017 5:25 PM, Joanna Kelley <notifications@github.com> wrote:That's not working before:

biocLite("biomformat")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.2 (BiocInstaller 1.20.3), R 3.3.2 (2016-10-31).
Installing package(s) ‘biomformat’
Warning message:
package ‘biomformat’ is not available (for R version 3.3.2)

**Comment by jokelley** [comment]
Great, I've updated it, is there any description of how to use the new version with QIIME because the QIIME commands fail.

**Comment by jokelley** [comment]
The example on this biom page doesn't work: http://biom-format.org/documentation/summarizing_biom_tables.html (I still get the same error)

**Comment by jnpaulson** [comment]
Sorry.  I don't use qiime. I'd recommend posting on their GitHub page. On Feb 15, 2017 5:51 PM, Joanna Kelley <notifications@github.com> wrote:The example on this biom page doesn't work: http://biom-format.org/documentation/summarizing_biom_tables.html (I still get the same error)

**Comment by jokelley** [comment]
Hi, that was directly from the http://biom-format.org website, I can't get it to work using the instructions there. Are there updated instructions somewhere?

**Comment by jokelley** [comment]
I see that you're different, apologies. I'll contact them. Cheers!

**Comment by aabversteeg** [comment]
Did you find the solution?
